Phase01
Star-Academy/Summer1401-FE-Team05 pull request #1
Opened 2022-07-20 08:16 UTC by HessamCheraghi

سلام هنوز کد اسلایدر رو وقت نکردیم بزنیم به نظرتون اشکالی نداره فعلا همین باشه یا اینکه به جاش یه پس زمینه ساده بزاریم ؟

2022-07-20 09:14 UTC, milar7 commented on src/app/components/header/header.component.ts
> +    }
به جای این کار یه بولین مثل isMobileNav بزارید بعد داخل اون تابع toggle ش کنید. داخل html هم اینجوری هندل کنید  

```html
<nav class="nav" [ngClass]="{open: isMobileNav}">
```

2022-07-20 09:15 UTC, milar7 commented on src/app/components/header/profile-btn/profile-btn.component.scss
> +    color: #fff;
hsl

2022-07-20 09:16 UTC, milar7 commented on src/app/components/header/profile-btn/profile-btn.component.scss
> +    border-radius: 14px;
همیشه از rem به جای px استفاده کنید

2022-07-20 09:16 UTC, milar7 commented on src/app/components/header/profile-btn/profile-btn.component.scss
> +        box-shadow: rgb(31 47 71 / 25%) 0px 20px 40px, rgb(0 0 0 / 10%) 0px 1px 5px,
hsl

2022-07-20 09:16 UTC, milar7 commented on src/app/components/header/profile-btn/profile-btn.component.scss
> +        box-shadow: rgb(31 47 71 / 25%) 0px 20px 40px, rgb(0 0 0 / 10%) 0px 1px 5px,
rem

2022-07-20 09:18 UTC, milar7 commented on src/app/components/header/search-box/search-box.component.scss
> +    color: #fff;
hsl

2022-07-20 09:18 UTC, milar7 commented on src/app/components/header/search-box/search-box.component.scss
> +    border-radius: 14px;
rem

2022-07-20 09:20 UTC, milar7 commented on src/app/components/header/profile-btn/profile-btn.component.scss
> +            rgb(255 255 255 / 40%) 0px 0px 0px 0.5px inset;
وقتی یه مقداری 0 هست نیازی به نوشتن واحد نیست. px پاک بشه. این موارد رو همه جا رعایت کنید

2022-07-20 09:25 UTC, milar7 commented on src/app/components/header/search-box/search-box.component.ts
> +    }
اینم مثل قبلی با یک بولیین و ngClass هندل کنید

2022-07-20 09:28 UTC, milar7 commented on src/app/pages/landing/carousel/carousel.component.scss
> +        }
پاک بشه

2022-07-20 09:32 UTC, milar7 commented on src/app/pages/landing/products/products.component.html
> +    <a *ngFor="let card of cards" href="#" class="game-card" dir="ltr">
مگه سایت فارسی نیست؟‌ پس چرا محتوای کارت‌ها رو اینگلیسی در نظر گرفتید؟ عوضش کنید

2022-07-20 09:33 UTC, milar7 commented on src/app/pages/landing/products/products.component.scss
> +            color: lightgreen;
این جور مقدار دهی ها پیشنهاد نمیشه. همش رو hsl کنید

2022-07-20 09:37 UTC, milar7 commented on src/app/pages/landing/products/products.component.ts
> +            title: 'abc',
اینو بزارید داخل یه فایل sample-data بعد اینجا ازش استفاده کنید

2022-07-20 09:38 UTC, milar7 commented on src/app/components/header/header.component.scss
> +    background-image: linear-gradient(45deg, rgba(24, 32, 79, 0.9) 0%, rgba(24, 32, 79, 0.85) 100%);
hsl

2022-07-20 09:49 UTC, HessamCheraghi commented on src/app/pages/landing/products/products.component.html
> +    <a *ngFor="let card of cards" href="#" class="game-card" dir="ltr">
درسته ولی اسم گیم ها که فارسی نیست

2022-07-20 10:14 UTC, milar7 commented on src/app/pages/landing/products/products.component.html
> +    <a *ngFor="let card of cards" href="#" class="game-card" dir="ltr">
اگه قراره همه‌ی محتوای داخل کارت اینگلیسی بمون مشکلی نداره ولی اگه بخواید بعدا مثلا یه دکمه فارسی اضافه کنید داخلش اشکال داره

2022-07-20 10:16 UTC, milar7 commented
> 

نه اشکالی نداره همینون بزارید بعدا تکمیلش کنید

2022-07-20 11:21 UTC, milar7 submitted a review, later dismissed

2022-07-24 05:38 UTC, arefhbb commented on src/app/components/header/header.component.scss
> +        transition: all 0.3s ease;
transition all nabashe

2022-07-24 05:42 UTC, arefhbb commented on src/app/components/header/profile-btn/profile-btn.component.scss
> +    transition: all 0.3s ease;
transition all

2022-07-24 05:43 UTC, arefhbb commented on src/app/components/header/header.component.scss
> +            transition: all 0.3s ease;
transition all

2022-07-24 05:44 UTC, arefhbb commented on src/app/components/header/header.component.scss
> +    transition: all 0.3s ease;
transition all

2022-07-24 05:45 UTC, arefhbb commented on src/app/components/header/search-box/search-box.component.scss
> +    transition: all 0.1s ease-in-out;
transition all

2022-07-24 05:56 UTC, arefhbb commented on src/app/components/header/header.component.scss
> +        background-color: #030130;
color -> hsl

2022-07-24 05:56 UTC, arefhbb commented on src/app/components/header/header.component.scss
> +        background-image: linear-gradient(45deg, rgb(3, 1, 50), rgb(0, 0, 0));
color -> hsl

2022-07-24 06:34 UTC, AliZoghi reviewed
به نظر همه چی درست میاد و نیازی به ویرایش اساسی نیست.

2022-07-24 06:34 UTC, AliZoghi commented on src/app/pages/landing/carousel/carousel.component.scss
> +    //display: flex;
کامنت پاک بشه

2022-07-24 06:34 UTC, AliZoghi commented on src/app/pages/landing/carousel/carousel.component.scss
> +.carousel-control {
چون فعلا صرفا از اسلایدر به عنوان عکس استفاده کردید میتونه این قسمت کد کلا پاک بشه

2022-07-24 06:34 UTC, AliZoghi commented on src/app/components/footer/footer.component.scss
> +        margin-bottom: 1rem;
بجای margin دادن میشه از فلکس در پرنت استفاده کرد

2022-07-24 06:34 UTC, AliZoghi commented on src/app/components/header/header.component.scss
> +        background-color: #030130;
تبدیل به hsl

2022-07-24 06:34 UTC, AliZoghi commented on src/app/components/header/header.component.scss
> +        background-image: linear-gradient(45deg, rgb(3, 1, 50), rgb(0, 0, 0));
تبدیل به hsl

2022-07-24 07:07 UTC, arefhbb requested changes

2022-07-24 07:07 UTC, arefhbb commented on src/app/components/header/profile-btn/profile-btn.component.scss
> +    transition: all 0.3s ease;
transition all

2022-07-24 08:07 UTC, arefhbb approved these changes

2022-07-24 08:16 UTC, AliZoghi approved these changes

2022-07-24 08:31 UTC, Alirezab-2000 commented on README.md
> +Run `npm run build` to build the project. The built project will be saved in the dist/ directory.
این فایل رو یه کامل کنید و یه readme خوب بنویسید طبق doc

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/app.module.ts
> +import {AppRoutingModule} from './app-routing.module';
پاک کردن فاصله اضافی

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/components/footer/footer.component.html
> +<footer class="footer">
کلاس footer رو توی scss ندیدم. اگر اضافی هست پاکش کنید

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/components/footer/footer.component.spec.ts
> +import {FooterComponent} from './footer.component';
فاصله اضافی بین import ها

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/components/header/header.module.ts
> +import { ProfileBtnModule } from './profile-btn/profile-btn.module';
space اضافی زده شده. prettier رو اعمال کنید روش

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/components/header/profile-btn/profile-btn.component.spec.ts
> +import {ProfileBtnComponent} from './profile-btn.component';
فاصله اضافی بین import ها

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/components/header/search-box/search-box.component.html
> +    </div>
کامنت های اضافی پاک بشن

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/components/header/search-box/search-box.component.scss
> +
از قابلیت nested که scss داره میتونید بیشتر استفاده کنید، مثلا کلاس search-label رو ببرید داخل کلاس search-box چون توی html هم داخل هم هستن

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/components/header/search-box/search-box.component.spec.ts
> +import {SearchBoxComponent} from './search-box.component';
فاصله اضافی

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/components/header/search-box/search-box.component.ts
> +import {NgxPopperjsPlacements} from 'ngx-popperjs';
فاصله اضافی

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/pages/landing/carousel/carousel.component.html
> +            <a routerLink="/" class="btn">نمایش دسته بندی ها</a>
به نظرم یه prettier لازم داره. اون فاصله اضافی های قبلی هم احتمالا با prettier اوکی بشن

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/pages/landing/carousel/carousel.component.spec.ts
> +import {CarouselComponent} from './carousel.component';
همون قضیه فاصله اضافی

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/pages/landing/landing.component.spec.ts
> +import {LandingComponent} from './landing.component';
بازم همون قضیه.

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/pages/landing/products/products.component.scss
> +    background-color: hsl(9, 100%, 64%);
اینجاهم باز فکر میکنم از قابلیت nested داخل scss میتونید استفاده کنید

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/pages/landing/products/products.component.spec.ts
> +import {ProductsComponent} from './products.component';
بازم همون قضیه. فایلای test تون فکر کنم این مشکل رو دارن. با یه prettier زد هم فکر کنم اوکی بشن

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/app/pages/not-found/not-found.component.spec.ts
> +import {NotFoundComponent} from './not-found.component';
همون

2022-07-24 08:31 UTC, Alirezab-2000 commented on src/main.ts
> +import {AppModule} from './app/app.module';
همون

2022-07-24 08:48 UTC, HessamCheraghi commented on src/app/components/footer/footer.component.spec.ts
> +import {FooterComponent} from './footer.component';
ما اومدیم بین کمپوننت هایی که ایمپورت کردیم و امپورت های خود انگولار فاصله گذاشتیم که قاطی نشه.

2022-07-24 08:48 UTC, AtaReversei reviewed
خسته نباشین دوستان

2022-07-24 08:48 UTC, AtaReversei commented on src/app/app.module.ts
> +    providers: [],
empty provider

2022-07-24 08:48 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +    list-style: none;
یعی کنید استایل هاتون رو دسته بندی کنید، اونایی که مثلا مربوط به فلکسن یه جا بعدش یه اینتر و بعدش مثلا لیست استایل

2022-07-24 08:48 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +            transition: all 0.3s ease;
بهتره ترنزیشن ها با میلی ثانیه نوشته بشه تا با جاوا اسکریپت استایلش یکی باشه

2022-07-24 08:48 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +    transition: all 0.3s ease;
بازم همون میلی ثانیه

2022-07-24 08:48 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +        transition: all 0.3s ease;
میلی ثانیه

2022-07-24 08:48 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +        right: 0;
inset-inline-start and inset-block-top usage

2022-07-24 08:48 UTC, AtaReversei commented on src/app/components/header/profile-btn/profile-btn.component.scss
> +    transition: all 0.3s ease;
میلی ثانیه

2022-07-24 08:48 UTC, AtaReversei commented on src/app/components/header/search-box/search-box.component.scss
> +        top: 50%;
بازم قضیه استفاده از inset-block و inset-inline

2022-07-24 08:48 UTC, AtaReversei commented on src/app/components/header/search-box/search-box.component.scss
> +    outline: none;
بهتره واسه این ها یه استایل گلوبال داشته باشین واسه تمامی المنت هایی که تو فرم استفاده میشن مثل اینپوت و باتن و تکست و باقی المنت ها که اوت لاین و بوردر زشت دارن

2022-07-24 08:48 UTC, AtaReversei commented on src/app/components/header/search-box/search-box.component.scss
> +    transition: all 0.1s ease-in-out;
میلی ثانیه

2022-07-24 08:48 UTC, AtaReversei commented on src/app/pages/landing/carousel/carousel.component.scss
> +    transition: opacity 0.3s ease-in-out;
میلی ثانیه

2022-07-24 08:48 UTC, AtaReversei commented on src/app/pages/landing/products/products.component.scss
> +        font-weight: bold;
بهتره از عدد 700 استفاده کنین، چون بالاتر هم از عدد واسه رگیولار کردن استفاده کردین فردا اگه نیاز شد تغییرش بدین حداقل میدونین باید دنبال عدد یا کلید واژه باشین

2022-07-24 08:48 UTC, AtaReversei commented on src/app/pages/landing/products/sample-data.ts
> +        alt: 'عکسی RDR2',
بهتره alt عکس رو توصیف کنه که داخلش چیا اتفاق میفتن، چون که تایتل رو هم دارین و اسکرین ریدر این رو هم میخونه و دوباره کاری میشه

2022-07-24 08:48 UTC, AtaReversei commented on src/styles.scss
> +
بهتره فونت رو از داخل HTML با لینک واردش کنین

2022-07-24 08:49 UTC, HessamCheraghi commented on src/app/components/header/header.module.ts
> +import { ProfileBtnModule } from './profile-btn/profile-btn.module';
درست شد ممنون

2022-07-24 09:30 UTC, HessamCheraghi commented on src/styles.scss
> +
ما میخوایم فونتی که داریم اعداد رو فارسی نشون بده گشتم لینکی براش پیدا نکردم برای همین توی css اضافه ش کردم

2022-07-24 10:10 UTC, AtaReversei approved these changes

2022-07-24 10:17 UTC, Alirezab-2000 approved these changes

2022-07-24 10:41 UTC, milar7 requested changes

2022-07-24 10:41 UTC, milar7 commented on src/app/components/footer/footer.component.scss
> +    margin-bottom: 4rem;
از margin  سعی کنید استفاده نکنید و با padding یا gap هندل کنید.
ثانیا اگه جایی هم مجبور بودید این می‌شد margin-block-end باید استفاده کنید

2022-07-24 10:41 UTC, milar7 commented on src/app/components/footer/footer.component.scss
> +        margin-bottom: 1rem;
گفتم

2022-07-24 10:41 UTC, milar7 commented on src/app/components/footer/footer.component.scss
> +    margin-bottom: 2rem;
گفتم

2022-07-24 10:41 UTC, milar7 commented on src/app/components/header/header.component.html
> +                <img src="assets/logos/NG-Store-logo.svg" alt="" width="160" />
inline-style قابل قبول نیست. width

2022-07-24 10:41 UTC, milar7 commented on src/app/components/header/header.component.scss
> +        left: 0;
از inset-inline و inset-block-start استفاده کنید

2022-07-24 10:41 UTC, milar7 commented on src/app/components/header/header.component.scss
> +            transition: background-color 0.2s ease;
انیمیشن فقط opacity و transform قابل قبول هست و دیگر هیچ!

2022-07-24 10:41 UTC, milar7 commented on src/app/components/header/search-box/search-box.component.scss
> +        padding-left: 4.2rem;
padding-inline-start

2022-07-24 10:41 UTC, milar7 commented on src/app/pages/landing/carousel/carousel.component.html
> +        <div class="header-container-inner">
به نظر میخواستی اسم کلاس رو طبق BEM بدی که در اون صورت میشه header-container__inner . اگه نه که هیچی :)

2022-07-24 10:41 UTC, milar7 commented on src/app/pages/landing/carousel/carousel.component.scss
> +        left: 50%;
inset-inline-start, inset-block-start

2022-07-24 10:41 UTC, milar7 commented on src/app/pages/landing/products/products.component.scss
> +    left: 0;
گفتم

2022-07-24 11:28 UTC, milar7 approved these changes

2022-07-24 12:19 UTC, BijanEisapour requested changes

2022-07-24 12:19 UTC, BijanEisapour commented on .eslintrc.json
> +                        "prefix": ["app", "icon", "illustration"],
واقعاً از اینا استفاده میکنید؟

2022-07-24 12:19 UTC, BijanEisapour commented on .github/workflows/deploy.yml
> +jobs:
جاب تست کو؟

2022-07-24 12:19 UTC, BijanEisapour commented on README.md
> +ما در پروژه از نُد و انگولار 12.2.1 استفاده کرده ایم لذا برای اجرای پروژه نیاز به نصب آن ها وجود دارد
نُد آخه؟

2022-07-24 12:19 UTC, BijanEisapour commented on README.md
> +# NgStore
لینک به CONTRIBUTING.md کو؟
بعد چرا اون فایل خالیه؟

2022-07-24 12:19 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +            <li><i class="fa-solid fa-circle-phone"></i> <span> 021-4444-4444</span></li>
چندتا space اضافی میبینم

2022-07-24 12:19 UTC, BijanEisapour commented on src/app/components/footer/footer.component.html
> +        <div class="enamad"><img src="assets/images/trustseal/enamad.png" alt="نماد اعتماد الکترونیکی" /></div>
x

2022-07-24 12:19 UTC, BijanEisapour commented on src/app/pages/landing/carousel/carousel.component.html
> +    <div class="header-container">
به نظر اضافی میرسن

2022-07-24 12:19 UTC, BijanEisapour commented on src/app/pages/landing/products/products.component.html
> +                <h3 class="game-card__title">{{ card.title }}</h3>
card__info__title

2022-07-24 12:19 UTC, BijanEisapour commented on src/app/pages/landing/products/products.component.html
> +                <div class="price-container">
چرا یه جا از bem استفاده کردید یه جا نکردید؟
یکپارچه باشه همه جا

2022-07-24 12:19 UTC, BijanEisapour commented on src/app/pages/landing/products/sample-data.ts
> +        price: 150000,
150_000

2022-07-24 12:19 UTC, BijanEisapour commented on src/app/pages/not-found/not-found.component.html
> +<p>not-found works!</p>
غ

2022-07-24 14:42 UTC, BijanEisapour requested changes
باید stylelint هم داشته باشید

2022-07-24 14:42 UTC, BijanEisapour commented on .github/workflows/deploy.yml
> +    test:
باید تو قسمت deploy اینو جزء needs بذارید 
مثه چیزی که تو داک داریم

2022-07-24 14:42 UTC, BijanEisapour commented on package.json
> +        "test:ci": "echo 'Test was passed.'",
😐

2022-07-25 14:56 UTC, BijanEisapour approved these changes

2022-07-26 04:35 UTC, merged

2022-07-27 16:53 UTC, HessamCheraghi commented
فاز اول تکمیل شد