[ADD] sign-up and sign-in
Star-Academy/Summer1401-FE-Team05 pull request #2
Opened 2022-07-26 05:03 UTC by SinaMAmini

فاز ثبت نام و ورود انجام شد

2022-07-26 17:32 UTC, AliZoghi commented on src/app/pages/sign-up/sign-up.component.ts
> +            console.log('email is not validate', this.user.email);
همه دیباگ کردنا برای نسخه نهایی باید پاک شه

2022-07-26 17:32 UTC, AliZoghi commented on src/app/services/api.service.ts
> +        console.log(data);
گفتم

2022-07-26 17:32 UTC, AliZoghi commented on src/app/pages/sign-up/sign-up.component.ts
> +        const validation = this.isValidate(this.user);
جایی بکار رفته؟

2022-07-26 17:32 UTC, AliZoghi commented on src/app/pages/sign-up/sign-up.component.scss
> +        border-radius: 3px;
unit

2022-07-26 17:32 UTC, AliZoghi commented on src/app/pages/sign-up/sign-up.component.scss
> +                border-radius: 1px;
نمیگم

2022-07-26 17:32 UTC, AliZoghi commented on src/app/pages/sign-up/sign-up.component.ts
> +// import {Router} from '@angular/router';
کامنت ها پاک بشن

2022-07-26 18:11 UTC, ArefHbb commented on src/app/app.module.ts
> +    imports: [
فقط باید ماژول های pages ایمپورت بشه نیازی به این همه ماژول ایمپورت کردن نیس

2022-07-26 18:11 UTC, ArefHbb commented on src/app/app.module.ts
> +    imports: [
چرا 2 تا imports دارید؟

2022-07-26 18:11 UTC, ArefHbb commented on src/app/services/api.service.spec.ts
> +import {TestBed} from '@angular/core/testing';
فایل gitkeep. را از پوشه services پاک کنید

2022-07-27 04:09 UTC, AtaReversei commented on src/app/pages/sign-up/sign-up.component.html
> +            نام کاربری
تو sign-up ما به دو تا field دیگه نیاز داریم، به نام و نام خانوادگی. البته برای اینکه فرآیند ثبت نام سریعتر اتفاق بیفته و کاربر معطل نشه میشه بعد ثبت نام تو پروفایلش مجابش کرد اسمش وارد کنه

2022-07-27 04:09 UTC, AtaReversei commented on src/app/pages/sign-up/sign-up.component.scss
> +            }
استایل های این button و after و beforeش رو میتونید تو استایل global قرار بدید تا کد تکراری نزنید، ممکنه جاهای دیگه هم استفادش کنید

2022-07-27 04:09 UTC, AtaReversei commented on src/app/pages/sign-up/sign-up.component.ts
> +    public isValidate(_user: User): boolean {
اینجا اسمتون یکم اشتباه داره، isValid درسته

2022-07-27 04:50 UTC, SinaMAmini commented on src/app/services/auth.service.ts
> +            localStorage.setItem('token', data?.token);
به نظرم اون علامت سوال میگه اگه data خودش undefined نبود؛ بره داحخلشو بررسی کنه
که اگه undefined  باشه اونوقت داخلش token وجود نداره و برنامه ارور میده...

2022-07-27 04:57 UTC, SinaMAmini commented on src/app/app.module.ts
> +    imports: [
این یه دونست و به معنی اینه که (قرمزه)قبلی دلیت شد... و سبزه(جدیده) اضافه شد

2022-07-27 04:57 UTC, SinaMAmini commented on src/app/services/api.service.spec.ts
> +import {TestBed} from '@angular/core/testing';
پاک شد

2022-07-27 04:57 UTC, SinaMAmini commented on src/app/pages/sign-in/sign-in.component.html
> +        <label *ngIf="isSignUp" class="input-label">
درسته و حذف شد.

2022-07-27 04:57 UTC, SinaMAmini commented on src/app/pages/sign-in/sign-in.component.scss
> +        border-radius: 1px;
برطرف شد

2022-07-27 05:04 UTC, SinaMAmini commented on src/app/pages/sign-up/sign-up.component.ts
> +            console.log('email is not validate', this.user.email);
حذف شد

2022-07-27 05:04 UTC, SinaMAmini commented on src/app/services/api.service.ts
> +        console.log(data);
حذف شد

2022-07-27 05:04 UTC, SinaMAmini commented on src/app/pages/sign-up/sign-up.component.ts
> +        const validation = this.isValidate(this.user);
ممنون یادآوری کردی؛ درست شد

2022-07-27 05:04 UTC, SinaMAmini commented on src/app/pages/sign-up/sign-up.component.scss
> +        border-radius: 3px;
اصلاح شد

2022-07-27 05:04 UTC, SinaMAmini commented on src/app/pages/sign-up/sign-up.component.scss
> +                border-radius: 1px;
اصلاح شد

2022-07-27 05:04 UTC, SinaMAmini commented on src/app/pages/sign-up/sign-up.component.ts
> +// import {Router} from '@angular/router';
پاک شد

2022-07-27 05:04 UTC, SinaMAmini commented on src/app/services/auth.service.ts
> +            localStorage.setItem('token', data?.token);
بالاتر توضیح دادم

2022-07-27 05:05 UTC, SinaMAmini commented on src/app/app.module.ts
> +    imports: [
آخه همشو تو اپ استفاده کردیم

2022-07-27 05:14 UTC, SinaMAmini commented on src/app/pages/sign-in/sign-in.component.html
> +        <label *ngIf="isSignUp" class="input-label">
پاک شد

2022-07-27 05:15 UTC, AliZoghi approved these changes

2022-07-27 05:17 UTC, Alirezab-2000 commented on src/app/pages/sign-in/sign-in.component.scss
> +    }
چون یه قسمتی از استایل هاشون یکی هستن برای جلوگیری از نوشتن کد dublicate به نظرم خوب بود اول جفتشون رو select کنید و بعد استایل های مشترک رو بدید. تو مرحله بعد یکی یکی select کنیدشون و استایل های غیر مشترک رو بدید. به اینصورت زیر
```
&::after, &::before{
        content: "";

        background-color: hsl(221deg 33% 19%);

        position: absolute;
        inset-block-end: 0;
        inset-inline-start: 0;

        width: 2rem;
        height: 1.5rem;
}
&::before{
        border-inline-start: 0.2rem solid hsl(261deg 56% 51%);

        transform: translate(-70%, -70%) rotate(45deg);
}
&::after{
        transform: translate(70%, 70%) rotate(45deg);
        border-inline-end: 0.2rem solid hsl(261deg 56% 51%);
}
```

2022-07-27 05:17 UTC, Alirezab-2000 commented on src/app/pages/sign-in/sign-in.component.ts
> +    public isSignUp: boolean = false;
به نظرم این متغیر اضافی تعریف شده. چون همه جا مقدارش false هست عملا تو کد html هم اون بخش داخل ngif رو نشون نمیده، اگر قصد استفاده دارید ازش استفاده کنید اگرنه هم خودش و هم بخش html مربوط بهش رو پاک کنید
متغیر داحل خط 16 منظورمه

2022-07-27 05:17 UTC, Alirezab-2000 commented on src/app/services/api.service.ts
> +        if (response.status === 200 || response.status === 201) return data as T;
به نظرم اگر از response.ok استفاده کنید هم خوانا تره هم اینکه از status code شماره 200 تا 209 رو پوشش میده و مقدار true برمیگردونه. بعدا ممکنه یه status code با شماره مثلا 205 بیاد ولی این متدتون اون رو قبول نکنه. علاوه بر این خواناییش هم بیشتره

2022-07-27 05:17 UTC, Alirezab-2000 commented on src/app/services/auth.service.ts
> +import {Token} from '../models/token.model';
این فاصله های اضافی به نظرم پاک بشن بهتره

2022-07-27 05:17 UTC, Alirezab-2000 commented on src/app/utils/urls.ts
> +export const BASE_URL = 'https://games.bijanprogrammer.com';
این هم بیژن base url جدید رو توی گروه گذاشت. تغییرش بدید که به مشکل نخورید یه وقت

2022-07-27 05:23 UTC, SinaMAmini commented on src/app/pages/sign-in/sign-in.component.ts
> +    public isSignUp: boolean = false;
بله حذف شد

2022-07-27 05:24 UTC, SinaMAmini commented on src/app/utils/urls.ts
> +export const BASE_URL = 'https://games.bijanprogrammer.com';
تغییر داده شد ممنون

2022-07-27 05:25 UTC, SinaMAmini commented on src/app/services/auth.service.ts
> +import {Token} from '../models/token.model';
برای راحتی فهم خودمون گذاشتیم
اول انگولار بعد  utility بعد سرویس ها بعد مدل ها

2022-07-27 05:26 UTC, ArefHbb approved these changes

2022-07-27 05:48 UTC, SinaMAmini commented on src/app/pages/sign-in/sign-in.component.scss
> +    }
البته `inset-block-end: 0; inset-inline-start: 0;` و `inset-block-start: 0; inset-inline-end: 0;`  فرق دارن ولی بقیش درسته باید تغییر بدم

2022-07-27 05:48 UTC, SinaMAmini commented on src/app/components/header/profile-btn/profile-btn.component.html
> +<a routerLink="profile" class="nav-btn">
درست شد

2022-07-27 05:49 UTC, SinaMAmini commented on src/app/pages/sign-in/sign-in.component.scss
> +    color: hsl(261deg 90% 95%);
در اسرع وقت که وقت گیر بیارم این پالت های رنگی رو هم درست میکنیم

2022-07-27 05:54 UTC, SinaMAmini commented on src/app/pages/sign-up/sign-up.component.scss
> +            }
استایل ها کمی تغییر کردن و کد تکراری کمتر شد

2022-07-27 05:56 UTC, SinaMAmini commented on src/app/pages/sign-up/sign-up.component.ts
> +    public isValidate(_user: User): boolean {
خب validate  فعل هست و باعث میشه فعل passive بشه یعنی تفاوت در "معتبر است" و "معتبر شده است" هست که واقعاً مهمه؟

2022-07-27 06:01 UTC, SinaMAmini commented on src/app/components/header/profile-btn/profile-btn.component.html
>      <i class="fa-regular fa-user-large"></i>
درست شد

2022-07-27 06:03 UTC, SinaMAmini commented on src/app/pages/sign-in/sign-in.component.scss
> +    height: 100vh;
درست شد

2022-07-27 06:06 UTC, AtaReversei approved these changes

2022-07-27 06:22 UTC, milar7 requested changes

2022-07-27 06:22 UTC, milar7 commented on src/app/components/header/sign-in-up/sign-in-up.component.html
> +    <i class="fa-solid fa-right-to-bracket"></i>
یه title واسه آیکون بزارید تا کاربر بفهمه این چیه. یکم شبیه آیکون خروج هست تا login . البته دکمه ورود/ثبت‌نام بزارید خیلی بهتره و با مفهوم تره

2022-07-27 06:22 UTC, milar7 commented on src/app/pages/sign-up/sign-up.component.ts
> +    }
این کار اصلا لازم نیست. واسه اون فیلد هایی که میخواید حتما پر بشن require بزارید و اسه فیلد ایمیل هم تایپ که email باشه خود مرور هندل میکنه. واسه اینکه ببینید form حالا valid هست یا نه یه آید مثلا #form بدید بهش بعد از تابع form.checkValidity استفاده کنید.
این تابع که نوشتید پاک بشه

2022-07-27 06:24 UTC, milar7 commented on src/app/pages/sign-up/sign-up.component.ts
> +    }
این تابع داخل sign in هم هست. اونم حذف بشه

2022-07-27 06:29 UTC, Alirezab-2000 commented on src/app/pages/sign-in/sign-in.component.scss
> +    color: hsl(261deg 90% 95%);
بسیار عالی

2022-07-27 06:31 UTC, Alirezab-2000 approved these changes

2022-07-27 08:12 UTC, milar7 approved these changes

2022-07-27 09:35 UTC, msrazavi requested changes

2022-07-27 09:35 UTC, msrazavi commented on src/app/pages/profile/profile.component.html
> +    <button (click)="logout()">خروج از حساب کاربری</button>
با کلیک روی دکمه خروج 404 می‌دهد.

2022-07-27 09:35 UTC, msrazavi commented on src/app/pages/sign-in/sign-in.component.html
> +        <button class="submit-btn" type="submit">ورود</button>
با اولین بار کلیک روی ورود 404 می‌دهد.

2022-07-27 09:35 UTC, msrazavi commented on src/app/components/header/header.component.ts
>      }
خوبه در navbar بعد از کلیک روی خانه و ریدایرکت شدن به خانه navbar خودش بسته شود.

2022-07-27 09:35 UTC, msrazavi commented on src/app/components/header/sign-in-up/sign-in-up.component.html
> +    <!--    <i class="fa-solid fa-right-to-bracket"></i>-->
کامنت حذف شود.

2022-07-27 09:35 UTC, msrazavi commented on src/app/pages/landing/products/products.component.scss
>      max-width: 80%;
logical

2022-07-27 09:35 UTC, msrazavi commented on src/app/pages/sign-up/sign-up.component.scss
> +                position: absolute;
بهتر است به جای absolute با flex هندل شود.

2022-07-27 09:35 UTC, msrazavi commented on src/app/pages/sign-up/sign-up.component.scss
> +                height: 1.5rem;
logical

2022-07-27 09:35 UTC, msrazavi commented on src/app/pages/landing/products/products.component.html
>          <a *ngFor="let card of cards" href="#" class="game-card">
بهتر است به جای href از router استفاده شود.

2022-07-27 09:45 UTC, SinaMAmini commented on src/app/pages/sign-up/sign-up.component.scss
> +                position: absolute;
این یه یکی از گوشه های button هست که کمی هم چرخیده و از transform استفاده کردیم؛ من راهی به ذهنم نمیرسه با flex انجام بشه

2022-07-27 10:11 UTC, SinaMAmini commented on src/app/pages/profile/profile.component.html
> +    <button (click)="logout()">خروج از حساب کاربری</button>
این اتفاق فقط تو gh-pages میوفته که دلیلشو نمیدونه ولی از منتور میپرسم

2022-07-27 12:20 UTC, SinaMAmini commented on src/app/pages/landing/products/products.component.html
>          <a *ngFor="let card of cards" href="#" class="game-card">
اصلاح شد

2022-07-27 12:20 UTC, SinaMAmini commented on src/app/pages/sign-up/sign-up.component.scss
> +                height: 1.5rem;
اصلاح شد

2022-07-27 12:20 UTC, SinaMAmini commented on src/app/pages/landing/products/products.component.scss
>      max-width: 80%;
اصلاح شد

2022-07-27 12:20 UTC, SinaMAmini commented on src/app/components/header/sign-in-up/sign-in-up.component.html
> +    <!--    <i class="fa-solid fa-right-to-bracket"></i>-->
حذف شد

2022-07-27 12:20 UTC, SinaMAmini commented on src/app/components/header/header.component.ts
>      }
انجام شد

2022-07-27 12:28 UTC, msrazavi approved these changes

2022-07-27 14:31 UTC, BijanEisapour requested changes

2022-07-27 14:31 UTC, BijanEisapour commented on src/app/pages/sign-up/sign-up.component.scss
> +        border-radius: 3px;
کجا اصلاح شد؟

2022-07-27 14:31 UTC, BijanEisapour commented on src/app/pages/sign-up/sign-up.component.scss
> +            font-weight: 400;
پیشفرض 
دیگه نمیگم

2022-07-27 14:31 UTC, BijanEisapour commented on src/app/pages/sign-up/sign-up.component.ts
> +            const isInfoOK = await this.authService.signUp(this.user);
camelCase
isInfoOk

2022-07-27 14:31 UTC, BijanEisapour commented on src/app/pages/sign-up/sign-up.component.ts
> +            const isInfoOK = await this.authService.signUp(this.user);
بعدشم اصن یه اسم بهتر بذارید 
حتی result یا response هم از این بهتره

2022-07-27 14:31 UTC, BijanEisapour commented on src/app/services/api.service.ts
> +    public constructor() {}
x

2022-07-27 14:31 UTC, BijanEisapour commented on src/app/services/api.service.ts
> +
ree

2022-07-27 14:31 UTC, BijanEisapour commented on src/app/services/auth.service.ts
> +            localStorage.setItem('token', data?.token);
چیزی که عارف میگه درسته 
اصلاح کن

2022-07-27 14:31 UTC, BijanEisapour commented on src/styles.scss
> -    src: url("assets/fonts/webfonts/Vazirmatn-RD-FD-Regular.woff2") format("woff2");
فایلش رو هم پاک کردی؟

2022-07-27 15:25 UTC, SinaMAmini commented on src/app/components/header/header.component.scss
> +            inline-size: 100%;
ما flex-direction رو column گذاشتیم ...
ما میخواستیم کل width صفحه رو بگیره

2022-07-27 15:35 UTC, SinaMAmini commented on src/app/services/api.service.ts
> +
یعنی چی؟

2022-07-27 15:43 UTC, SinaMAmini commented on src/app/services/auth.service.ts
> +            localStorage.setItem('token', data?.token);
درسته الان فهمیدم و درستش کردم

2022-07-27 15:43 UTC, SinaMAmini commented on src/app/pages/sign-up/sign-up.component.scss
> +        border-radius: 3px;
این دفعه واقعاً اصلاح شد :)))

2022-07-27 15:46 UTC, SinaMAmini commented on src/styles.scss
> -    src: url("assets/fonts/webfonts/Vazirmatn-RD-FD-Regular.woff2") format("woff2");
پاک شد

2022-07-27 16:40 UTC, BijanEisapour approved these changes

2022-07-27 16:44 UTC, HessamCheraghi commented on src/app/components/header/header.component.scss
> +    block-size: 100%;
همه رو حذف کردیم

2022-07-27 16:45 UTC, HessamCheraghi commented on src/app/components/header/header.component.scss
> +            inline-size: 100%;
این رو هم برای موبایل گذاشته بودیم، الان حذفش کردیم، یکم کد رو عوض کردیم به این نیازی نداشته باشیم.

2022-07-27 16:47 UTC, HessamCheraghi commented on src/app/pages/sign-in/sign-in.component.scss
> +    font-weight: 400;
توی کل فایل ها سرچ کردیم و درستش کردیم

2022-07-27 16:49 UTC, HessamCheraghi commented on src/app/services/api.service.ts
> +
مخفف 
`
Remove Extra Enter 
`
هست درست شد

2022-07-27 16:52 UTC, merged

2022-07-27 16:52 UTC, HessamCheraghi commented
فاز دوم تکمیل شد