Phase03
Star-Academy/Summer1401-FE-Team05 pull request #3
Opened 2022-08-02 03:24 UTC by HessamCheraghi

بالاخره به درصد 80 رسیدیم!

2022-08-02 05:34 UTC, Negarnbkhti42 commented on src/app/app.component.scss
> +    min-height: 100vh;
استفاده از logical properties

2022-08-02 05:35 UTC, Negarnbkhti42 commented on src/app/components/header/header.component.scss
> +        top: 100%;
گفته شد

2022-08-02 05:35 UTC, Negarnbkhti42 commented on src/app/components/header/header.component.html
> +            <a routerLink="sign-in" class="sign-in-btn">ورود/ثبت‌نام</a>
/ قبل از مسیر جا افتاده است

2022-08-02 05:36 UTC, Negarnbkhti42 commented on src/app/components/header/header.component.scss
> +                    transition: opacity ease 300ms;
بهتره که همه جا از یه واحد استفاده بشه (ترجیحا ثانیه)

2022-08-02 05:40 UTC, Negarnbkhti42 commented on src/app/components/header/header.component.scss
> +@media (min-width: 60em) {
لزومی به استفاده از em در اینجا هست؟

2022-08-02 05:56 UTC, Negarnbkhti42 commented on src/app/pages/landing/landing.component.spec.ts
> +            imports: [CarouselModule, ProductsModule, RouterTestingModule],
فکر نمیکنم نیازی به ایمپورت کردم ماژول های carousel و product باشه

2022-08-02 05:57 UTC, Negarnbkhti42 commented on src/app/pages/landing/products/products.component.spec.ts
> +    it('should only one h3 tag per card', () => {
should only "have"

2022-08-02 06:20 UTC, Alirezab-2000 commented on src/app/app.component.scss
> +    min-height: 100vh;
logical

2022-08-02 06:20 UTC, Alirezab-2000 commented on src/app/components/header/header.component.scss
> +        transition: transform 0.3s ease;
از میلی ثانیه استفاده کنید بهتره چون فکر میکنم بقیه جاها هم از میلی ثانیه استفاده کردید

2022-08-02 06:20 UTC, Alirezab-2000 commented on src/app/components/header/header.component.scss
> +    color: hsl(0deg 0% 100%);
سعی کنید این رنگ ها رو به پالت رنگی اضافه کنید و بعد از متغیرشون استفاده کنید

2022-08-02 06:20 UTC, Alirezab-2000 commented on src/app/components/header/header.component.scss
> +    color: hsl(0deg 0% 100%);
گفته شد

2022-08-02 06:27 UTC, dibaaamir requested changes

2022-08-02 06:27 UTC, dibaaamir commented on src/app/app.component.scss
> +    min-height: 100vh;
logical

2022-08-02 06:27 UTC, dibaaamir commented on src/app/components/header/header.component.html
> +            <input type="search" name="search" placeholder="جست و جو" /> <i class="fa-regular fa-magnifying-glass"></i>
نیم فاصله بزنید بهتره جست‌و‌جو

2022-08-02 06:27 UTC, dibaaamir commented on src/app/components/header/header.component.scss
> +        min-height: calc(100vh - 100%);
logical هم این هم بالاییش

2022-08-02 06:27 UTC, dibaaamir commented on src/app/components/header/header.component.scss
> +                width: 100%;
logical

2022-08-02 06:27 UTC, dibaaamir commented on src/app/components/header/header.component.scss
> +    color: hsl(0deg 0% 100%);
اینارو به صورت var بدید بهتره. مثلا یه پالت درست کنید از رنگ ها.

2022-08-02 06:27 UTC, dibaaamir commented on src/app/components/header/header.component.scss
> +                border-radius: 0.3rem;
طبق گفته اقای عیسی پور بهتره که حداکثر دو نوع border radius داشته باشیم یکی برای بزرگترا یکی برای کوچیک ترا و یکی بدیم همه جا

2022-08-02 06:29 UTC, AtaReversei approved these changes

2022-08-02 06:29 UTC, AtaReversei commented on src/app/components/header/header.component.html
> +                <i class="fa-solid fa-user-large"></i>
بهتره از آیکون های هماهنگ استفاده کنید 
یا regular یا solid

2022-08-02 06:29 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +        width: 100%;
inline-size

2022-08-02 06:29 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +            max-width: 60rem;
logical

2022-08-02 06:29 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +                outline: none;
استایل هایی مثل این هی تکرار میشن، بهتره در استایل global قرار بدینشون

2022-08-02 06:29 UTC, AtaReversei commented on src/app/components/header/header.component.scss
> +                    transition: opacity ease 300ms;
جاوا اسکریپت از میلی ثانیه استفاده میکنه، واسه همین بهتره از میلی ثانیه استفاده کنیم به نظر من

2022-08-02 06:29 UTC, AtaReversei commented on src/app/pages/sign-in/sign-in.component.spec.ts
> +    it('test handleSubmit with empty inputs', async () => {
بهتره از یه اسم برای تست ها استفاده کنید 
یا should یا tests

2022-08-02 06:29 UTC, dorrin-sot requested changes

2022-08-02 06:29 UTC, dorrin-sot commented on src/app/components/header/header.component.scss
> +                top: 50%;
logical

2022-08-02 06:29 UTC, dorrin-sot commented on src/app/components/header/header.component.spec.ts
> +    it('should open and close mobile navbar properly', () => {
این تست و تست بعد میتونن توی یه for روی لیست [true, false] باشن و expect نهایی بصورت (toBe(isMobileNavOpen باشه

2022-08-02 06:29 UTC, dorrin-sot commented on src/app/pages/sign-in/sign-in.component.spec.ts
> +    it('tests handleSubmit with correct username and password', async () => {
باتوجه به اینکه همه‌جا از should استفاده کردید اینجا هم تغییر بدید (جاهای دیگه هم همینطور)

2022-08-02 06:30 UTC, dibaaamir requested changes

2022-08-02 06:30 UTC, dibaaamir commented on src/app/components/header/header.component.html
> +            <li><a routerLink="/">دسته بندی ها</a></li>
نیم فاصله

2022-08-02 06:30 UTC, dibaaamir commented on src/app/components/header/header.component.scss
> +                top: 50%;
logical

2022-08-02 06:33 UTC, dibaaamir requested changes

2022-08-02 06:33 UTC, dibaaamir commented on src/app/components/header/header.component.scss
> +            max-width: 60rem;
logical

2022-08-02 06:38 UTC, dorrin-sot requested changes

2022-08-02 06:38 UTC, dorrin-sot commented on src/app/pages/sign-up/sign-up.component.spec.ts
> +        component.handleSubmit();
چیزی تست نکردین که (همچنین بالایی)

2022-08-02 06:38 UTC, dorrin-sot commented on src/app/pages/sign-in/sign-in.component.spec.ts
> +        component.handleSubmit();
گفته شد (هیچ expectای نداره)

2022-08-02 07:12 UTC, Negarnbkhti42 commented on src/app/services/auth.service.ts
> +        this.isLoggedIn().then();
میتونه به ngOnInit منتقل بشه تا لازم به زدن then نباشه

2022-08-02 07:13 UTC, Negarnbkhti42 commented on src/app/services/auth.service.spec.ts
> +    it('tests isLoggedIn - with wrong token', async () => {
از یک فرمت برای نام تست ها استفاده بشه

2022-08-02 08:04 UTC, msrazavi requested changes

2022-08-02 08:04 UTC, msrazavi commented on package.json
> +        "TestSpecInclude": "ng test --include=**/services/*.spec.ts",
چرا فقط پوشه سرویس هاردکد شده؟

2022-08-02 08:04 UTC, msrazavi commented on src/app/pages/landing/products/products.component.html
> -                <h3 class="overview__title">{{ card.title }}</h3>
استفاده از h ها برای تایتل بهتر است.

2022-08-02 10:19 UTC, HessamCheraghi commented on src/app/components/header/header.component.scss
> +@media (min-width: 60em) {
میخواستیم از پیکسل استفاده نکنیم واسه همین گذاشتیم

2022-08-02 10:49 UTC, HessamCheraghi commented on src/app/pages/landing/carousel/carousel.component.html
> -</header>
تگ هدر رو بردیم به کمپوننت هدر

2022-08-02 10:52 UTC, HessamCheraghi commented on package.json
> +        "TestSpecInclude": "ng test --include=**/services/*.spec.ts",
واسه اینکه راحت تر تست بگیریم استفاده میکردیم الان پاکش کردم

2022-08-02 10:53 UTC, HessamCheraghi commented on src/app/pages/landing/products/products.component.html
> -                <h3 class="overview__title">{{ card.title }}</h3>
این جا دو تا h3 داشتیم که هر دو یکی هستند قراره کارت کامل عوض بشه ولی درستش کردم

2022-08-02 11:11 UTC, Alirezab-2000 approved these changes

2022-08-02 11:48 UTC, HessamCheraghi commented on src/app/pages/sign-up/sign-up.component.spec.ts
> +        component.handleSubmit();
ممنون یادمون رفته بود الان درستش کردیم

2022-08-02 11:49 UTC, dibaaamir approved these changes

2022-08-02 11:54 UTC, dorrin-sot approved these changes

2022-08-02 11:59 UTC, SinaMAmini commented on src/app/services/auth.service.ts
> +        this.isLoggedIn().then();
اون .then برای اینه که حواسمون به async بودن isLoggedIn باشه

2022-08-02 18:00 UTC, msrazavi approved these changes

2022-08-06 13:52 UTC, BijanEisapour approved these changes

2022-08-06 13:52 UTC, BijanEisapour commented on src/app/components/header/header.component.spec.ts
> +
ree

2022-08-06 13:52 UTC, BijanEisapour commented on src/app/guards/auth.guard.spec.ts
>  import {AuthGuard} from './auth.guard';
چرا تست نشده؟

2022-08-06 13:52 UTC, BijanEisapour commented on src/app/pages/profile/profile.component.ts
> +export const WINDOW = new InjectionToken('Window');
نیازی به این نیس
مستقیم از window استفاده کنید

2022-08-06 13:52 UTC, BijanEisapour commented on src/app/pages/sign-in/sign-in.component.spec.ts
> +    });
v

2022-08-06 13:52 UTC, BijanEisapour commented on src/app/pages/sign-in/sign-in.component.spec.ts
> +        const passwordInput = host.querySelector('[type="password"][name="password"]');
چرا فقط از name استفاده نکردید؟

2022-08-06 13:52 UTC, BijanEisapour commented on src/app/pages/sign-in/sign-in.component.ts
> +    @ViewChild('SignInForm') private signInForm!: ElementRef<HTMLFormElement>;
cameCase

2022-08-06 13:52 UTC, BijanEisapour commented on src/app/pages/sign-up/sign-up.component.spec.ts
> +        const emailInput = host.querySelector('[type="email"][name="email"]');
نمیگم

2022-08-07 12:14 UTC, merged